### ISSUE TITLE
On settings page add to catact it type

### ISSUE THREAD

**Issue by tantra35** [moira-alert/web#11]
When we use twilio, there is possible 2 types of service, twilio sms and twilio voice, they have the same ico, so it is unclear which is which
![twilio-contecttype](https://cloud.githubusercontent.com/assets/1377084/12403268/f8a1e6fe-be43-11e5-929e-124a98679a4b.jpg)

to fix this we use follow patch
[twilio-contacttype.zip](https://github.com/moira-alert/web/files/95023/twilio-contacttype.zip)

**Comment by gmlexx** [comment]
It is not a good design solution. Use different icons. Color it to blue for sms, e.g.
