### ISSUE TITLE
Add possibility to duplicate(copy) trigger

### ISSUE THREAD

**Issue by tantra35** [moira-alert/web#12]
When needed create many same triggers, much better duplicate prototype, then copy paste

**Comment by gmlexx** [comment]
1) You can use import/export. 
- First, export trigger (small gray icon at main list).
- Edit trigger.json and make id empty.
- Add new trigger and press import. Imported trigger will acquire new id and saved as new trigger.

2) You can use link to create new trigger:
http://localhost/#/trigger/?name=NewTrigger&target=NewTarget&ttl=600&ttl_state=NODATA&warn_value=50&error_value=1000

The latter has limitation: you can set only one target

**Comment by tantra35** [comment]
You agree, that simple click  on duplicate button much simpler :-)

**Comment by gmlexx** [comment]
Yes, I'm not rejecting this feature.

**Comment by gmlexx** [comment]
Add copy button @0d03295 v1.0.6
