### ISSUE TITLE
Add pagination on main page

### ISSUE THREAD

**Issue by beevee** [moira-alert/web#14]
With hundreds of triggers, main page is loading very slow. See attached screenshot.

There is one enormous API request (1.5MB, several seconds), but JS execution also takes nearly a second.

https://yadi.sk/i/qcMfWTyAqMGFA

I think, pagination or server-side filtering is an option to solve this problem.

**Comment by gmlexx** [comment]
Made some boost on API request by pipeline of redis requests. 
https://github.com/moira-alert/worker/commit/33b841af0ebe9125cdf68b81221e05a6d25bc249

**Comment by gmlexx** [comment]
Released in v1.1.1
