### ISSUE TITLE
Show all targets in web

### ISSUE THREAD

**Issue by titusjaka** [moira-alert/web#15]
Hi!
I've configured a moira trigger and created 2 targets. Nevertheless I could see only one target in web:
![](https://disk.skbkontur.ru/index.php/s/BwttKsO6kfdXu6e/download)

Could you please show all targets?
Thank you in advance!

**Comment by gmlexx** [comment]
Fixed in https://github.com/moira-alert/worker/commit/8a1ec994117e702566aa56589c3530b4cb93f929
