### ISSUE TITLE
Is it possible to add graphite expression preview like cabot does

### ISSUE THREAD

**Issue by tantra35** [moira-alert/web#2]
In link bellow, cabot can preview graphite expression. This is very useful. It will be cool if moira will do the same.

http://cabotapp.com/use/graphite-checks.html

**Comment by gmlexx** [comment]
We'd thought about this. But when you created new check, the data is not in cache yet.
So, there is nothing to display for some time without falling back to graphite API.

Also, if you have graphite, you must have grafana :)
In practice it is more convenient to copy-paste expression from grafana to moira.
In our fork we even add such link to grafana (some ugly hard-coded way, but works) https://github.com/skbkontur/grafana/commits/skbkontur2

**Comment by tantra35** [comment]
Not all metrics we watch throw graphana, so something that allow debug graphite expression highly desirable, it's not problem to link with graphite api url, becouse graphite alredy used

**Comment by beevee** [comment]
Graphite independence is a degisn decision. Currently we don't rely on Graphite API or storage at all: you can use KairosDB or InfluxDB or really nothing at all as a permanent storage. I think, introducing Graphite dependency would be a bad choice here.

**Comment by beevee** [comment]
For me, the best workflow is:
1. Plot some graphs in Graphite Web interface, see the real data and determine appropriate thresholds.
2. Copy and paste Graphite expression from Graphite Web interface into Moira.

Entering expressions manually into Moira Web interface is a bad idea: without seeing the graphs you can easily make a mistake.
