### ISSUE TITLE
Add export trigger button, instead removed from main menu

### ISSUE THREAD

**Issue by gmlexx** [moira-alert/web#28]

**Comment by beevee** [comment]
We have export button on trigger page :)

**Comment by gmlexx** [comment]
Really? I can see only import button.

**Comment by beevee** [comment]
![2016-05-07_00-39-54](https://cloud.githubusercontent.com/assets/1009675/15084352/b05e660e-13f4-11e6-897a-d157fa0abe9f.png)

**Comment by gmlexx** [comment]
👍
