### ISSUE TITLE
Current state of metric doesn't changed

### ISSUE THREAD

**Issue by tantra35** [moira-alert/web#3]
![state-doesn t-chnage](https://cloud.githubusercontent.com/assets/1377084/12250586/2a792a36-b8d9-11e5-9244-dc87999fb070.jpg)

As show on screenshot, last change of current state was 11 minutes ago, but metric on screenshot will change more dynamically(faster), but moira doesn't show last values(only moment of switch between states), so It might give the impression that the system is not working

**Comment by gmlexx** [comment]
This is events history page and like others page it is not updated automatically (yet).
Current state shows the latest metric value. It may be equal to event value accidentally, but not necessarily (as you can see in attached screenshot)
Also current state event time - is last event that trigger this metric to that state.

![2016-01-12 11 49 11](https://cloud.githubusercontent.com/assets/1112318/12256820/8ee93594-b922-11e5-8196-592693761d46.png)

**Comment by tantra35** [comment]
Ok, I transform question :-) Is it possible to add somewhere, last metric value? So becomes possible to see actualy state of system. Something like "Last value"

**Comment by gmlexx** [comment]
Click on state balloon at main page

**Comment by tantra35** [comment]
It also show only last value of check, but we need current value

**Comment by gmlexx** [comment]
Checks run every 5 sec (by default). Standard metrics retentions is one minute.
So, new values should arrive every minute. Otherwise some values will ignored.

Checks and it's values are updated 6 time frequently.
You will see latest value almost all time.

**Comment by tantra35** [comment]
Ahhh, yes value is chnaged, but filed "last event time" no, so i have little confusion about this.
![moira-notupdatedmetric](https://cloud.githubusercontent.com/assets/1377084/12263227/7b5d8720-b93e-11e5-823d-4f61ba9f37bb.png)

**Comment by gmlexx** [comment]
Yea, event occurs only if state changed. ok -> warn, warn->ok, etc
There is no last metric time, but may be should.

NODATA TTL is responsible to inform you, that no fresh metrics income for a some period.
