### ISSUE TITLE
Remaining maintenance time is "few seconds" for almost all metrics

### ISSUE THREAD

**Issue by beevee** [moira-alert/web#32]
![2016-05-07_12-49-49](https://cloud.githubusercontent.com/assets/1009675/15090945/ad085760-145a-11e6-8734-15b8d5a8be37.png)

UI shows "a few seconds" for metrics that are not in maintenance mode. Manually setting "done" helps.

**Comment by beevee** [comment]
You can see it on our staging site.

**Comment by gmlexx** [comment]
I've got it. Will fix later, or you can do it
https://github.com/moira-alert/web/blob/master/static/app/directives/maintenance.ts
line 51
scope.check.json.maintenance  can be undefined

сб, 7 мая 2016 г. в 10:52, Alexey Kirpichnikov notifications@github.com:
