### ISSUE TITLE
Need pagination for /#/events/*

### ISSUE THREAD

**Issue by eugenea** [moira-alert/web#47]
aliasByNode(collectd.*.swap.swap-free,1) produces roughtly 1500 metrics.

If you click on that trigger it crashes browser because the list is too long and takes lots of browser memory.

That page needs to have some pagination.

the wort part is that "Edit" button is on that page too.

**Comment by gmlexx** [comment]
That kind of pagination will takes some time.
For trigger edit you can hold alt key and click on trigger from the /triggers/ page.

**Comment by beevee** [comment]
This is obsolete, since we are planning to release a whole new UI in the near future.
