### ISSUE TITLE
Add pagination on event history page

### ISSUE THREAD

**Issue by tantra35** [moira-alert/web#6]
For example if count of triggers or EVENT HISTORY will by 10000 and more records. What moira will do? On another words, is any paging functionality? In source code i doesn't see any lines abot this

**Comment by gmlexx** [comment]
Internally events are stored for 30 days for each trigger.
UI fetching last 100 events.
Paging is possible in future.

**Comment by tantra35** [comment]
Ah ok. So it not possible situation when on one page show 10000x records, which can freez any brouser?

**Comment by gmlexx** [comment]
10000 records is not a big problem even for angular applications on modern browsers.
UI is not optimized for such case yet. Trigger with 1000 metrics can unfolding for a few seconds.

**Comment by tantra35** [comment]
Hm my FF brouser works not very well on such count of records, but google chrome works perfectly
