### ISSUE TITLE
On add trigger UI page in the buttons labels are moved

### ISSUE THREAD

**Issue by tantra35** [moira-alert/web#7]
![moira-ui-bug](https://cloud.githubusercontent.com/assets/1377084/12351678/792df35a-bb90-11e5-9cf9-dc3a973b7953.png)

**Comment by beevee** [comment]
Please, tell us your browser version and screen resolution.

**Comment by tantra35** [comment]
ff, google chome have the same result, for test we looking this page on ie11, situation is the same

1280x1024

**Comment by gmlexx** [comment]
Fixed in latest release.
