### ISSUE TITLE
probably makes sense to use webpack plugin UglifyJsPlugin, to reduce final js size

### ISSUE THREAD

**Issue by tantra35** [moira-alert/web#9]

**Comment by gmlexx** [comment]
There is a few reason, why we didn't use that:
1) This is internal web application, that will accessed by LAN network in most cases, gzip content encoding works also.

2) At the beginning, fast bug fixes has higher priority than faster application loading.

I didn't find a solution how to see source typescript code (via map files) if additional uglifyjs transformation take place.

3) Like for material design js, css we can use minified versions of angular and others fat modules.

**Comment by tantra35** [comment]
We also use it only in internal network, but altime exists vpn, which can be slow

**Comment by gmlexx** [comment]
UglifyJsPlugin seems working. Added it in v1.0.3.min
